CREATE TABLE IF NOT EXISTS collect_runtime_statuses (
    circuit_key VARCHAR(50) NOT NULL,
    open_until  DATETIME,
    created_at  DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at  DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    PRIMARY KEY (circuit_key)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
