ALTER TABLE users
    ADD COLUMN IF NOT EXISTS notification_email_yn BOOLEAN NOT NULL DEFAULT TRUE,
    ADD COLUMN IF NOT EXISTS notification_in_app_yn BOOLEAN NOT NULL DEFAULT TRUE,
    ADD COLUMN IF NOT EXISTS notification_web_push_yn BOOLEAN NOT NULL DEFAULT FALSE;

ALTER TABLE user_profiles
    ADD COLUMN IF NOT EXISTS notification_email_yn BOOLEAN NOT NULL DEFAULT TRUE,
    ADD COLUMN IF NOT EXISTS notification_in_app_yn BOOLEAN NOT NULL DEFAULT TRUE,
    ADD COLUMN IF NOT EXISTS notification_web_push_yn BOOLEAN NOT NULL DEFAULT FALSE;
