import {
  AdminDashboardAlertsCard,
  AdminDashboardSnapshotCard,
  AdminDashboardTopHeader,
} from "./AdminDashboardTopPanels";

export default function AdminDashboardTopSection({
  windowDays,
  onWindowDaysChange,
  isRefreshing,
  onRefreshAll,
  promotedAttentionItems,
  attentionQueueItems,
  latestGeneratedAt,
  failedSectionCount,
  openCircuitCount,
  retryGroupCount,
  recoveredGroupCount,
  wrapperMissingAllStandardCodes,
  wrapperMissingDeltaLabel,
  wrapperMissingDeltaColor,
  wrapperMissingStandardCodeTone,
  wrapperAttentionFeedPrimaryTitle,
  wrapperAttentionFeedItemCount,
  wrapperAttentionFeedPrimarySource,
  wrapperAttentionFeedPrimarySeverity,
  wrapperAttentionFeedTone,
  wrapperAttentionFeedPrimaryActionLabel,
  wrapperAttentionFeedPrimaryKey,
  wrapperAttentionFeedPrimaryTargetId,
  wrapperRecommendationObservationStatus,
  wrapperActiveBaselineReuseLabel,
  wrapperObservationChangeLabel,
  wrapperAttentionFeedStatus,
  wrapperObservationChangeColor,
  wrapperSnapshotAlert,
  standardCodeCoverage,
  standardCodeEffectObservation,
  wrapperObservation,
  officialCodebooks,
  breakdowns,
  collectFailures,
  searchFailures,
  onJumpToSection,
}) {
  return (
    <>
      <AdminDashboardTopHeader
        windowDays={windowDays}
        onWindowDaysChange={onWindowDaysChange}
        isRefreshing={isRefreshing}
        onRefreshAll={onRefreshAll}
      />
      <AdminDashboardAlertsCard
        promotedAttentionItems={promotedAttentionItems}
        attentionQueueItems={attentionQueueItems}
        onJumpToSection={onJumpToSection}
      />
      <AdminDashboardSnapshotCard
        attentionQueueItems={attentionQueueItems}
        latestGeneratedAt={latestGeneratedAt}
        failedSectionCount={failedSectionCount}
        openCircuitCount={openCircuitCount}
        retryGroupCount={retryGroupCount}
        recoveredGroupCount={recoveredGroupCount}
        wrapperMissingAllStandardCodes={wrapperMissingAllStandardCodes}
        wrapperMissingDeltaLabel={wrapperMissingDeltaLabel}
        wrapperMissingDeltaColor={wrapperMissingDeltaColor}
        wrapperMissingStandardCodeTone={wrapperMissingStandardCodeTone}
        wrapperAttentionFeedPrimaryTitle={wrapperAttentionFeedPrimaryTitle}
        wrapperAttentionFeedItemCount={wrapperAttentionFeedItemCount}
        wrapperAttentionFeedPrimarySource={wrapperAttentionFeedPrimarySource}
        wrapperAttentionFeedPrimarySeverity={wrapperAttentionFeedPrimarySeverity}
        wrapperAttentionFeedTone={wrapperAttentionFeedTone}
        wrapperAttentionFeedPrimaryActionLabel={wrapperAttentionFeedPrimaryActionLabel}
        wrapperAttentionFeedPrimaryKey={wrapperAttentionFeedPrimaryKey}
        wrapperAttentionFeedPrimaryTargetId={wrapperAttentionFeedPrimaryTargetId}
        wrapperRecommendationObservationStatus={wrapperRecommendationObservationStatus}
        wrapperActiveBaselineReuseLabel={wrapperActiveBaselineReuseLabel}
        wrapperObservationChangeLabel={wrapperObservationChangeLabel}
        wrapperAttentionFeedStatus={wrapperAttentionFeedStatus}
        wrapperObservationChangeColor={wrapperObservationChangeColor}
        wrapperSnapshotAlert={wrapperSnapshotAlert}
        standardCodeCoverage={standardCodeCoverage}
        standardCodeEffectObservation={standardCodeEffectObservation}
        wrapperObservation={wrapperObservation}
        officialCodebooks={officialCodebooks}
        breakdowns={breakdowns}
        collectFailures={collectFailures}
        searchFailures={searchFailures}
        onJumpToSection={onJumpToSection}
      />
    </>
  );
}
