server:
  forward-headers-strategy: framework

spring:
  autoconfigure:
    exclude:
      - org.springframework.boot.autoconfigure.security.servlet.UserDetailsServiceAutoConfiguration

  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}

  jpa:
    open-in-view: false

  data:
    redis:
      host: ${REDIS_HOST}
      port: ${REDIS_PORT}

  mail:
    host: ${MAIL_HOST:smtp.gmail.com}
    port: ${MAIL_PORT:587}
    username: ${MAIL_USERNAME:${GMAIL_USERNAME}}
    password: ${MAIL_PASSWORD:${GMAIL_PASSWORD}}
    properties:
      mail:
        smtp:
          auth: ${MAIL_SMTP_AUTH:true}
          starttls:
            enable: ${MAIL_SMTP_STARTTLS_ENABLE:true}

app:
  base-url: ${APP_BASE_URL}
  mail:
    provider: ${MAIL_PROVIDER:smtp}
    from-address: ${MAIL_FROM_ADDRESS:${MAIL_USERNAME:${GMAIL_USERNAME}}}
    reply-to: ${MAIL_REPLY_TO:${MAIL_FROM_ADDRESS:${MAIL_USERNAME:${GMAIL_USERNAME}}}}
  datasource:
    pii-rw:
      url: ${APP_PII_DB_URL}
      username: ${DB_APP_PII_USERNAME}
      password: ${DB_APP_PII_PASSWORD}
    notification-pii-ro:
      url: ${NOTIFICATION_PII_DB_URL}
      username: ${DB_NOTIFICATION_PII_RO_USERNAME}
      password: ${DB_NOTIFICATION_PII_RO_PASSWORD}

security:
  cors:
    allowed-origins: ${SECURITY_CORS_ALLOWED_ORIGINS}
